### ISSUE TITLE
404 - not found - Running core-2021.3.0b0 with internal URL

### ISSUE THREAD

**Issue by smith844** [home-assistant/my.home-assistant.io#33]
Tried to implement my.home-assistant.io  my URL is: `Your instance URL: http://192.168.1.205:8123` 

Whenever it tries to redirect i get page not available, my address bar via my.home-assistant.io for the config page for example is http://192.168.1.205:8123/_my_redirect/config
this is not a good link, when i manually select it this is a good link
http://192.168.1.205:8123/config
i am not sure if it is relevant but i am running nginx proxy manager, duckdns, ad-guard and dnsmasq.  
I am sorry if i am doing something wrong, i am a gifted amateur at best, but if its not working for me, perhaps its not working for someone else.
Also, if this is in the wrong place please let me know and i will move it and add whatever detail you need.

**Comment by frenck** [comment]
Sounds like the 'my' integration is not loaded. This can be caused by not using the 'default_config' in your configuration. 

'default_config' is normally there by default, but if removed or swapped for individual configurations manually, update like these require manual intervention by the user.

If this is the case for you as well, you could add 'my:' to your YAML configuration to activate it, or add back 'default_config:'.

**Comment by smith844** [comment]
It did of course fix it.  I added my: to my config.yaml.

Legend!
